// Datos para simular conversaciones en el chat.

export default {
  names: [
    'María',
    'Sandra',
    'Carla',
    'Juliana',
    'Yurley',
    'Mariana',
    'Sofía',
    'Patricia',
    'Natalia',
    'Tatiana',
    'Lina',
    'Andrea',
    'Catalina',
    'Katy',
    'Inés',
    'Juan',
    'Andrés',
    'Carlos',
    'Camilo',
    'Santiago',
    'José',
    'Iván',
    'Sergio',
    'Julián',
    'Francisco',
    'William',
    'Romel',
    'Pepe',
    'Pedro',
    'Jesús'
  ],
  surnames: [
    'González',
    'Rodríguez',
    'Gómez',
    'Fernández',
    'López',
    'Díaz',
    'Martínez',
    'Pérez',
    'García',
    'Sánchez',
    'Romero',
    'Sosa',
    'Álvarez',
    'Torres',
    'Ruiz',
    'Ramírez',
    'Flores',
    'Acosta',
    'Benítez',
    'Medina',
    'Suárez',
    'Herrera',
    'Aguirre',
    'Pereyra',
    'Gutiérrez',
    'Giménez',
    'Molina',
    'Silva',
    'Castro',
    'Rojas'
  ],
  phrases: [
    'A todo cerdo le llega su San Martín',
    'A vivir que son dos días',
    'A wet blanket',
    'Adonde fueres haz lo que vieres',
    'Agua que no has de beber déjala correr',
    'Ahogarse en un vaso de agua',
    'Cruzar los dedos',
    'Cuando a uno le quedan 2 telediarios',
    'Cuando algo es otro cantar',
    'Cuando algo o alguien es la bomba',
    'Dime cuánto (para comida o bebidas)',
    'Dios los cría y ellos se juntan',
    'Dorar la píldora',
    'Dormir como un ceporro',
    'Dormir la mona',
    'El uno por el otro la casa sin barrer',
    'En boca cerrada no entran moscas',
    'En casa de herrero, cuchillo de palo',
    'En el reino de los ciegos, el tuerto es el rey',
    'Llevar un buen pedo o ir pedo perdido',
    'Llevar un buen puntazo',
    'Llevar una buena cogorza',
    'Llevar una buena melopea',
    'Llevar una buena mierda encima',
    'Llevarse como el perro y el gato',
    'Llevarse el gato al agua',
    'No pegar ojo',
    'No pegar ni con cola',
    'No por mucho madrugar, amanece más temprano',
    'No se hizo la miel para la boca del asno',
    'No se puede vender la piel del oso antes de cazarlo',
    'Quédate con el cambio',
    'Quien evita la ocasión evita el peligro',
    'Quien siembra vientos recoge tempestades',
    'Si las barbas de tu vecino ves cortar, pon las tuyas a remojar',
    'Si lloras por no haber visto el Sol las lágrimas te impedirán ver las estrellas'
  ]
};
